#!/bin/bash -


case "$*" in 

start)
iptables -P INPUT DROP
iptables -I INPUT -s 21.21.130.0/24 -j ACCEPT
iptables -I INPUT -s 127.0.0.1 -j ACCEPT
iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
;;
stop)
iptables -P INPUT ACCEPT
iptables -F 
;;
restart)
$0 stop
$0 start
;;
status)
iptables -L -n -v -x
;;
*)
echo "recommence petit scarabe ..."
esac

